apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ (include "xwiki.initScripts" .) }}
  labels:
    {{- include "xwiki.labels" . | nindent 4 }}
data:
  entrypoint: |
    #!/bin/bash
    ##
    # *Experimental* solution for custom properties. 
    # With time we are looking other alternatives to setup this custom values. 
    ##
    # Always execute "first_start" in order to get all new values keys from future versions. 
    rm -f /usr/local/xwiki/data/xwiki.cfg
    rm -f /usr/local/xwiki/data/xwiki.properties
    rm -f /usr/local/xwiki/data/hibernate.cfg.xml

    # Reuse commands/resources from default entrypoint. 
    source /usr/local/bin/docker-entrypoint.sh
    file_env 'CONTEXT_PATH' 'ROOT'
    # Setup all default actions from first start
    first_start

    # Replace all values from keys defineded on customConfigs
    {{- range $file, $values := .Values.customConfigs }}
      {{- range $key, $value := $values }}
        # TODO review/manage extensions 
        if grep -wq "{{ $key }}" /usr/local/xwiki/data/{{ $file }}; then
          echo "Key ({{ $key }}) exists on file ({{ $file }}), replacing that key line with new value."
          xwiki_replace "/usr/local/xwiki/data/{{ $file }}" "{{ $key }}" "{{ $value }}" || true
        else 
          echo "Key ({{ $key }}) don't exists on file ({{ $file }}), appending that key line with new value."
          echo '{{ $key }} = {{ $value }}' >> "/usr/local/xwiki/data/{{ $file }}" || true
        fi
      {{- end }}
    {{- end }}

    ## Clear contents of /tmp/java_opts.txt so that we don't add extra arguments at each pod restart.
    echo "" > /tmp/java_opts.txt
    {{- range $file, $value := .Values.properties }}
      echo "-D{{ $file }}=\"{{ $value }}\"" >> /tmp/java_opts.txt
    {{- end }}
    export JAVA_OPTS="${JAVA_OPTS} @/tmp/java_opts.txt"

    {{- if .Values.glowroot.enabled }}
    mkdir -p /usr/local/xwiki/data/glowroot 
    GLOWROOT_VERSION="0.14.0" 
    if ! [ -d "/usr/local/xwiki/data/glowroot/glowroot-${GLOWROOT_VERSION}" ]; then 
      wget -O  /tmp/glowroot-${GLOWROOT_VERSION}-dist.zip https://github.com/glowroot/glowroot/releases/download/v${GLOWROOT_VERSION}/glowroot-${GLOWROOT_VERSION}-dist.zip 
      unzip /tmp/glowroot-${GLOWROOT_VERSION}-dist.zip -d /usr/local/xwiki/data/glowroot/
      rm -f /tmp/glowroot-${GLOWROOT_VERSION}-dist.zip 
      mv /usr/local/xwiki/data/glowroot/glowroot /usr/local/xwiki/data/glowroot/glowroot-${GLOWROOT_VERSION}
    fi 
    cp /configmaps/glowroot.properties /usr/local/xwiki/data/glowroot/glowroot-${GLOWROOT_VERSION}/glowroot.properties
    # Append first to enable user override agent. 
    export JAVA_OPTS=" -javaagent:/usr/local/xwiki/data/glowroot/glowroot-${GLOWROOT_VERSION}/glowroot.jar ${JAVA_OPTS}"
    {{- end }}

    exec /usr/local/bin/docker-entrypoint.sh xwiki
  glowroot.properties: |
    {{- with .Values.glowroot.properties }}
      {{- range $k, $v := . }}
        {{- printf "%s=%s" $k $v | nindent 4 }}
      {{- end }}
    {{- end }}